name: Validation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        composer:
          - 2
          - 1
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
        php:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
    name: PHP ${{ matrix.php }}; Composer v${{ matrix.composer }}; ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, json, mbstring, pcre
          ini-values: memory_limit=512M
          tools: composer:v${{ matrix.composer }}

      - name: Check PHP Version
        run: php -v

      - name: Checkout
        uses: actions/checkout@master
        with:
          path: main

      - name: Test simply package install (as not required; standalone)
        run: composer install --no-progress --no-dev --prefer-dist --optimize-autoloader
        working-directory: main

      - name: Creating test_app path for dummy project...
        run: mkdir test_app

      - name: Creating test_app/composer.json...
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: test_app/composer.json
          write-mode: overwrite
          contents: |
            {
              "name": "dummy/dummy",
              "description": "Dummy project to test if configuration works",
              "require": {
                "pantheon-se/node-composer": "@dev"
              },
              "repositories": [
                {
                  "type": "path",
                  "url": "../main/"
                }
              ],
              "extra": {
                "pantheon-se": {
                  "node-composer": {
                    "yarn-version": true
                  }
                }
              },
              "config": {
                "optimize-autoloader": true,
                "sort-packages": true,
                "bin-dir": "bin"
              }
            }
      - name: Trying to install test_app...
        run: composer install --no-progress --no-dev --optimize-autoloader -vvv
        working-directory: test_app

      - name: Test if installed node is working... (Windows)
        run: node --version
        working-directory: .\test_app\bin
        if: matrix.os == 'windows-latest'

      - name: Test if installed node is working... (Not Windows)
        run: node --version
        working-directory: ./test_app/bin
        if: matrix.os != 'windows-latest'

      - name: Test if installed yarn is working... (Windows)
        run: yarn --version
        working-directory: .\test_app\bin
        if: matrix.os == 'windows-latest'

      - name: Test if installed yarn is working... (Not Windows)
        run: yarn --version
        working-directory: ./test_app/bin
        if: matrix.os != 'windows-latest'